
{{- if .Values.clusterAccess.rbac.create -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  name: "{{ .Chart.Name }}-cr"
rules:
- apiGroups:
    - ""
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
- apiGroups:
    - extensions
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
    - apiGroups:
- apps
    resources: ["*"]
    verbs:
    - get
    - list
    - watch
---
apiVersion: {{ template "rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  name: "{{ .Chart.Name }}-crb"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Chart.Name }}-cr"
subjects:
  - kind: ServiceAccount
    name: "{{ .Chart.Name }}-sa"
    namespace: {{ template "alexandria.namespace" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  name: "{{ .Chart.Name }}-sa"
{{- end -}}